### ISSUE TITLE
intercept handling

### ISSUE THREAD

**Issue by jkurle** [beniaminogreen/cragg#1]
I have issues with the functions in the package when an intercept is included explicitly and when the model should not contain an intercept.

The following code models the intercept explicitly but throws an error. The reason is that it leads to two intercept columns in `X_m` that are of course perfectly collinear.
```r
df <- iris
df$CONS <- 1
cragg_donald(X=~CONS+Sepal.Length, D=~Sepal.Width, Z=~Petal.Length + Petal.Width + Species, data = df)
```
Similarly, the code internally always adds an intercept column to X_m but some models might not have an intercept.

It would be good to simply have a consistent handling of an intercept. It is possibly easiest if users need to specify an intercept explicitly by creating a variable and add it to the `~X` formula. Alternatively, a function argument could ask the user whether an intercept should be added or not.

**Comment by beniaminogreen** [comment]
Hi Jonas, 

Thank you for bringing this to my attention and for creating a reproducible example. I remember having to think hard about intercepts when creating the package and evidently it's still a challenge, so I will improve the documentation in the next version. 

In the example, you create a second intercept column in the iris dataframe, and use it for the model.  This is not the same as manually including an intercept, as you have both created a column with an intercept value and used the default intercept. 

You can explicitly turn the intercept off or on by adding a +1 or -1 in your formula. 

If you would like to turn the intercept off and on using a column in your dataframe,  you can do so using the following code: 

```r
df <- iris
df$CONS <- 1
cragg_donald(X=~CONS+Sepal.Length-1, D=~Sepal.Width, Z=~Petal.Length + Petal.Width + Species, data = df)
```
This code creates an intercept column and removes the default intercept, so there is no colinearity error. This is the same interface the classic modelling functions have in R. 

I hope this answers your questions, please let me know if it doesn't.

**Comment by jkurle** [comment]
Hi Beniamino,

Thanks for your quick reply. This actually resolves the issue, I did not know (and unfortunately didn't try) that the usual formula specification for excluding the intercept can be used in your commands as well.

As you said, it might be worth adding in your documentation that the default behaviour includes an intercept. I sometimes prefer creating an intercept directly if I need to do some other analysis following the estimation of the 2SLS model.

**Comment by beniaminogreen** [comment]
Will do, thanks for your feedback.
